/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : EntityId,
  'status' : AttendanceStatus,
  'date' : string,
  'staff_id' : EntityId,
  'clinic_id' : ClinicId,
  'check_out' : [] | [Timestamp],
  'check_in' : [] | [Timestamp],
}
export type AttendanceStatus = { 'halfDay' : null } |
  { 'present' : null } |
  { 'absent' : null };
export type BloodGroup = { 'abNeg' : null } |
  { 'abPos' : null } |
  { 'aNeg' : null } |
  { 'aPos' : null } |
  { 'bNeg' : null } |
  { 'bPos' : null } |
  { 'oNeg' : null } |
  { 'oPos' : null } |
  { 'unknown' : null };
export type ClinicId = bigint;
export interface ClinicSettings {
  'gst_number' : string,
  'name' : string,
  'email' : string,
  'clinic_id' : ClinicId,
  'address' : string,
  'working_hours' : WorkingHours,
  'phone' : string,
}
export type DentistId = bigint;
export interface Document {
  'id' : EntityId,
  'blob' : ExternalBlob,
  'mime_type' : string,
  'clinic_id' : ClinicId,
  'filename' : string,
  'owner_id' : EntityId,
  'uploaded_at' : Timestamp,
  'uploaded_by' : Principal,
  'owner_type' : string,
}
export type EntityId = bigint;
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface InventoryItem {
  'id' : ItemId,
  'updated_at' : Timestamp,
  'cost_price' : number,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'reorder_level' : number,
  'clinic_id' : ClinicId,
  'stock' : number,
  'expiry_date' : [] | [string],
  'category' : string,
}
export interface InventoryItemInput {
  'cost_price' : number,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'reorder_level' : number,
  'stock' : number,
  'expiry_date' : [] | [string],
  'category' : string,
}
export interface Invoice {
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'patient_id' : PatientId,
  'total' : number,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'gst_total' : number,
  'payment_history' : Array<Payment>,
  'items' : Array<InvoiceItem>,
  'subtotal' : number,
}
export type InvoiceId = bigint;
export interface InvoiceInput {
  'patient_id' : PatientId,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem {
  'gst_rate' : number,
  'description' : string,
  'amount' : number,
}
export type InvoiceStatus = { 'cancelled' : null } |
  { 'paid' : null } |
  { 'issued' : null } |
  { 'partiallyPaid' : null } |
  { 'draft' : null };
export type ItemId = bigint;
export interface LabOrder {
  'id' : LabOrderId,
  'status' : LabOrderStatus,
  'patient_id' : PatientId,
  'specifications' : string,
  'lab_name' : string,
  'cost' : number,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'completed_date' : [] | [string],
  'treatment_id' : [] | [TreatmentId],
  'notes' : string,
  'due_date' : string,
  'procedure_type' : string,
}
export type LabOrderId = bigint;
export interface LabOrderInput {
  'patient_id' : PatientId,
  'specifications' : string,
  'lab_name' : string,
  'cost' : number,
  'treatment_id' : [] | [TreatmentId],
  'notes' : string,
  'due_date' : string,
  'procedure_type' : string,
}
export type LabOrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Medication {
  'duration' : string,
  'dosage' : string,
  'name' : string,
  'notes' : string,
  'frequency' : string,
}
export interface Patient {
  'id' : PatientId,
  'updated_at' : Timestamp,
  'created_at' : Timestamp,
  'email' : string,
  'clinic_id' : ClinicId,
  'blood_group' : BloodGroup,
  'address' : string,
  'gender' : Gender,
  'first_name' : string,
  'last_name' : string,
  'date_of_birth' : string,
  'phone' : string,
  'medical_history' : string,
  'allergies' : Array<string>,
}
export type PatientId = bigint;
export interface PatientInput {
  'email' : string,
  'blood_group' : BloodGroup,
  'address' : string,
  'gender' : Gender,
  'first_name' : string,
  'last_name' : string,
  'date_of_birth' : string,
  'phone' : string,
  'medical_history' : string,
  'allergies' : Array<string>,
}
export interface Payment {
  'method' : PaymentMethod,
  'date' : Timestamp,
  'reference' : string,
  'amount' : number,
}
export type PaymentMethod = { 'upi' : null } |
  { 'other' : null } |
  { 'card' : null } |
  { 'cash' : null } |
  { 'cheque' : null } |
  { 'netBanking' : null };
export interface Prescription {
  'id' : PrescriptionId,
  'patient_id' : PatientId,
  'dentist_id' : DentistId,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'medications' : Array<Medication>,
  'treatment_id' : [] | [TreatmentId],
  'is_active' : boolean,
}
export type PrescriptionId = bigint;
export interface PrescriptionInput {
  'patient_id' : PatientId,
  'dentist_id' : DentistId,
  'medications' : Array<Medication>,
  'treatment_id' : [] | [TreatmentId],
}
export type ProcedureStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export type StaffId = bigint;
export interface StaffInput {
  'hire_date' : string,
  'license_number' : string,
  'principal' : Principal,
  'name' : string,
  'role' : StaffRole,
  'email' : string,
  'phone' : string,
  'qualification' : string,
}
export interface StaffMember {
  'id' : StaffId,
  'hire_date' : string,
  'license_number' : string,
  'principal' : Principal,
  'name' : string,
  'role' : StaffRole,
  'email' : string,
  'clinic_id' : ClinicId,
  'is_active' : boolean,
  'phone' : string,
  'qualification' : string,
}
export type StaffRole = { 'admin' : null } |
  { 'doctor' : null } |
  { 'receptionist' : null };
export type Timestamp = bigint;
export interface ToothChart {
  'id' : EntityId,
  'patient_id' : PatientId,
  'teeth' : Array<ToothEntry>,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'treatment_id' : [] | [TreatmentId],
}
export interface ToothEntry {
  'status' : ToothStatus,
  'dentist_id' : DentistId,
  'last_updated' : Timestamp,
  'procedure_type' : [] | [string],
  'tooth_number' : bigint,
}
export interface ToothProcedure {
  'status' : ProcedureStatus,
  'dentist_id' : DentistId,
  'notes' : string,
  'completed_at' : [] | [Timestamp],
  'procedure_type' : string,
  'tooth_number' : bigint,
}
export type ToothStatus = { 'missing' : null } |
  { 'other' : null } |
  { 'implant' : null } |
  { 'healthy' : null } |
  { 'filled' : null } |
  { 'extracted' : null } |
  { 'decayed' : null } |
  { 'crowned' : null };
export interface Treatment {
  'id' : TreatmentId,
  'status' : TreatmentStatus,
  'patient_id' : PatientId,
  'title' : string,
  'updated_at' : Timestamp,
  'procedures' : Array<ToothProcedure>,
  'dentist_id' : DentistId,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'notes' : string,
  'estimated_cost' : number,
}
export type TreatmentId = bigint;
export interface TreatmentInput {
  'patient_id' : PatientId,
  'title' : string,
  'procedures' : Array<ToothProcedure>,
  'dentist_id' : DentistId,
  'notes' : string,
  'estimated_cost' : number,
}
export type TreatmentStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkingHours {
  'close_time' : string,
  'days_open' : Array<string>,
  'open_time' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adjustInventoryStock' : ActorMethod<
    [EntityId, number],
    [] | [InventoryItem]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelInvoice' : ActorMethod<[EntityId], boolean>,
  'createInventoryItem' : ActorMethod<[InventoryItemInput], InventoryItem>,
  'createInvoice' : ActorMethod<[InvoiceInput], Invoice>,
  'createLabOrder' : ActorMethod<[LabOrderInput], LabOrder>,
  'createPatient' : ActorMethod<[PatientInput], Patient>,
  'createPrescription' : ActorMethod<[PrescriptionInput], Prescription>,
  'createStaffMember' : ActorMethod<[StaffInput], StaffMember>,
  'createTreatment' : ActorMethod<[TreatmentInput], Treatment>,
  'deactivatePrescription' : ActorMethod<[EntityId], boolean>,
  'deactivateStaffMember' : ActorMethod<[EntityId], boolean>,
  'deleteDocument' : ActorMethod<[EntityId], boolean>,
  'deleteInventoryItem' : ActorMethod<[EntityId], boolean>,
  'deleteLabOrder' : ActorMethod<[EntityId], boolean>,
  'deletePatient' : ActorMethod<[EntityId], boolean>,
  'deletePrescription' : ActorMethod<[EntityId], boolean>,
  'deleteTreatment' : ActorMethod<[EntityId], boolean>,
  'getAttendanceByDate' : ActorMethod<[EntityId, string], [] | [Attendance]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicSettings' : ActorMethod<[], [] | [ClinicSettings]>,
  'getDocument' : ActorMethod<[EntityId], [] | [Document]>,
  'getExpiryAlerts' : ActorMethod<[bigint], Array<InventoryItem>>,
  'getInventoryItem' : ActorMethod<[EntityId], [] | [InventoryItem]>,
  'getInvoice' : ActorMethod<[EntityId], [] | [Invoice]>,
  'getLabOrder' : ActorMethod<[EntityId], [] | [LabOrder]>,
  'getLowStockAlerts' : ActorMethod<[], Array<InventoryItem>>,
  'getPatient' : ActorMethod<[EntityId], [] | [Patient]>,
  'getPrescription' : ActorMethod<[EntityId], [] | [Prescription]>,
  'getStaffByPrincipal' : ActorMethod<[Principal], [] | [StaffMember]>,
  'getStaffMember' : ActorMethod<[EntityId], [] | [StaffMember]>,
  'getToothChart' : ActorMethod<[EntityId], [] | [ToothChart]>,
  'getTreatment' : ActorMethod<[EntityId], [] | [Treatment]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAttendance' : ActorMethod<
    [[] | [EntityId], [] | [string], [] | [string]],
    Array<Attendance>
  >,
  'listDocuments' : ActorMethod<[EntityId, string], Array<Document>>,
  'listInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'listInvoices' : ActorMethod<[[] | [EntityId]], Array<Invoice>>,
  'listLabOrders' : ActorMethod<[[] | [EntityId]], Array<LabOrder>>,
  'listPatients' : ActorMethod<[], Array<Patient>>,
  'listPrescriptions' : ActorMethod<[[] | [EntityId]], Array<Prescription>>,
  'listStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'listTreatments' : ActorMethod<[[] | [EntityId]], Array<Treatment>>,
  'recordAttendance' : ActorMethod<
    [EntityId, string, [] | [Timestamp], [] | [Timestamp], AttendanceStatus],
    Attendance
  >,
  'recordPayment' : ActorMethod<[EntityId, Payment], [] | [Invoice]>,
  'searchPatients' : ActorMethod<[string], Array<Patient>>,
  'updateClinicSettings' : ActorMethod<[ClinicSettings], ClinicSettings>,
  'updateInventoryItem' : ActorMethod<
    [EntityId, InventoryItemInput],
    [] | [InventoryItem]
  >,
  'updateInvoice' : ActorMethod<[EntityId, InvoiceInput], [] | [Invoice]>,
  'updateLabOrderStatus' : ActorMethod<
    [EntityId, LabOrderStatus, [] | [string]],
    [] | [LabOrder]
  >,
  'updatePatient' : ActorMethod<[EntityId, PatientInput], [] | [Patient]>,
  'updateStaffMember' : ActorMethod<[EntityId, StaffInput], [] | [StaffMember]>,
  'updateTreatment' : ActorMethod<[EntityId, TreatmentInput], [] | [Treatment]>,
  'uploadDocument' : ActorMethod<
    [EntityId, string, string, string, ExternalBlob],
    Document
  >,
  'upsertToothChart' : ActorMethod<
    [EntityId, [] | [EntityId], Array<ToothEntry>],
    ToothChart
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];