/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EntityId = IDL.Nat;
export const ItemId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ClinicId = IDL.Nat;
export const InventoryItem = IDL.Record({
  'id' : ItemId,
  'updated_at' : Timestamp,
  'cost_price' : IDL.Float64,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'reorder_level' : IDL.Float64,
  'clinic_id' : ClinicId,
  'stock' : IDL.Float64,
  'expiry_date' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InventoryItemInput = IDL.Record({
  'cost_price' : IDL.Float64,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'reorder_level' : IDL.Float64,
  'stock' : IDL.Float64,
  'expiry_date' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const PatientId = IDL.Nat;
export const InvoiceItem = IDL.Record({
  'gst_rate' : IDL.Float64,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const InvoiceInput = IDL.Record({
  'patient_id' : PatientId,
  'items' : IDL.Vec(InvoiceItem),
});
export const InvoiceId = IDL.Nat;
export const InvoiceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'paid' : IDL.Null,
  'issued' : IDL.Null,
  'partiallyPaid' : IDL.Null,
  'draft' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'other' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
  'netBanking' : IDL.Null,
});
export const Payment = IDL.Record({
  'method' : PaymentMethod,
  'date' : Timestamp,
  'reference' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'patient_id' : PatientId,
  'total' : IDL.Float64,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'gst_total' : IDL.Float64,
  'payment_history' : IDL.Vec(Payment),
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Float64,
});
export const TreatmentId = IDL.Nat;
export const LabOrderInput = IDL.Record({
  'patient_id' : PatientId,
  'specifications' : IDL.Text,
  'lab_name' : IDL.Text,
  'cost' : IDL.Float64,
  'treatment_id' : IDL.Opt(TreatmentId),
  'notes' : IDL.Text,
  'due_date' : IDL.Text,
  'procedure_type' : IDL.Text,
});
export const LabOrderId = IDL.Nat;
export const LabOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const LabOrder = IDL.Record({
  'id' : LabOrderId,
  'status' : LabOrderStatus,
  'patient_id' : PatientId,
  'specifications' : IDL.Text,
  'lab_name' : IDL.Text,
  'cost' : IDL.Float64,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'completed_date' : IDL.Opt(IDL.Text),
  'treatment_id' : IDL.Opt(TreatmentId),
  'notes' : IDL.Text,
  'due_date' : IDL.Text,
  'procedure_type' : IDL.Text,
});
export const BloodGroup = IDL.Variant({
  'abNeg' : IDL.Null,
  'abPos' : IDL.Null,
  'aNeg' : IDL.Null,
  'aPos' : IDL.Null,
  'bNeg' : IDL.Null,
  'bPos' : IDL.Null,
  'oNeg' : IDL.Null,
  'oPos' : IDL.Null,
  'unknown' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PatientInput = IDL.Record({
  'email' : IDL.Text,
  'blood_group' : BloodGroup,
  'address' : IDL.Text,
  'gender' : Gender,
  'first_name' : IDL.Text,
  'last_name' : IDL.Text,
  'date_of_birth' : IDL.Text,
  'phone' : IDL.Text,
  'medical_history' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const Patient = IDL.Record({
  'id' : PatientId,
  'updated_at' : Timestamp,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'clinic_id' : ClinicId,
  'blood_group' : BloodGroup,
  'address' : IDL.Text,
  'gender' : Gender,
  'first_name' : IDL.Text,
  'last_name' : IDL.Text,
  'date_of_birth' : IDL.Text,
  'phone' : IDL.Text,
  'medical_history' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const DentistId = IDL.Nat;
export const Medication = IDL.Record({
  'duration' : IDL.Text,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'frequency' : IDL.Text,
});
export const PrescriptionInput = IDL.Record({
  'patient_id' : PatientId,
  'dentist_id' : DentistId,
  'medications' : IDL.Vec(Medication),
  'treatment_id' : IDL.Opt(TreatmentId),
});
export const PrescriptionId = IDL.Nat;
export const Prescription = IDL.Record({
  'id' : PrescriptionId,
  'patient_id' : PatientId,
  'dentist_id' : DentistId,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'medications' : IDL.Vec(Medication),
  'treatment_id' : IDL.Opt(TreatmentId),
  'is_active' : IDL.Bool,
});
export const StaffRole = IDL.Variant({
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'receptionist' : IDL.Null,
});
export const StaffInput = IDL.Record({
  'hire_date' : IDL.Text,
  'license_number' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : StaffRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
});
export const StaffId = IDL.Nat;
export const StaffMember = IDL.Record({
  'id' : StaffId,
  'hire_date' : IDL.Text,
  'license_number' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : StaffRole,
  'email' : IDL.Text,
  'clinic_id' : ClinicId,
  'is_active' : IDL.Bool,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
});
export const ProcedureStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ToothProcedure = IDL.Record({
  'status' : ProcedureStatus,
  'dentist_id' : DentistId,
  'notes' : IDL.Text,
  'completed_at' : IDL.Opt(Timestamp),
  'procedure_type' : IDL.Text,
  'tooth_number' : IDL.Nat,
});
export const TreatmentInput = IDL.Record({
  'patient_id' : PatientId,
  'title' : IDL.Text,
  'procedures' : IDL.Vec(ToothProcedure),
  'dentist_id' : DentistId,
  'notes' : IDL.Text,
  'estimated_cost' : IDL.Float64,
});
export const TreatmentStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Treatment = IDL.Record({
  'id' : TreatmentId,
  'status' : TreatmentStatus,
  'patient_id' : PatientId,
  'title' : IDL.Text,
  'updated_at' : Timestamp,
  'procedures' : IDL.Vec(ToothProcedure),
  'dentist_id' : DentistId,
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'notes' : IDL.Text,
  'estimated_cost' : IDL.Float64,
});
export const AttendanceStatus = IDL.Variant({
  'halfDay' : IDL.Null,
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : EntityId,
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'staff_id' : EntityId,
  'clinic_id' : ClinicId,
  'check_out' : IDL.Opt(Timestamp),
  'check_in' : IDL.Opt(Timestamp),
});
export const WorkingHours = IDL.Record({
  'close_time' : IDL.Text,
  'days_open' : IDL.Vec(IDL.Text),
  'open_time' : IDL.Text,
});
export const ClinicSettings = IDL.Record({
  'gst_number' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'clinic_id' : ClinicId,
  'address' : IDL.Text,
  'working_hours' : WorkingHours,
  'phone' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : EntityId,
  'blob' : ExternalBlob,
  'mime_type' : IDL.Text,
  'clinic_id' : ClinicId,
  'filename' : IDL.Text,
  'owner_id' : EntityId,
  'uploaded_at' : Timestamp,
  'uploaded_by' : IDL.Principal,
  'owner_type' : IDL.Text,
});
export const ToothStatus = IDL.Variant({
  'missing' : IDL.Null,
  'other' : IDL.Null,
  'implant' : IDL.Null,
  'healthy' : IDL.Null,
  'filled' : IDL.Null,
  'extracted' : IDL.Null,
  'decayed' : IDL.Null,
  'crowned' : IDL.Null,
});
export const ToothEntry = IDL.Record({
  'status' : ToothStatus,
  'dentist_id' : DentistId,
  'last_updated' : Timestamp,
  'procedure_type' : IDL.Opt(IDL.Text),
  'tooth_number' : IDL.Nat,
});
export const ToothChart = IDL.Record({
  'id' : EntityId,
  'patient_id' : PatientId,
  'teeth' : IDL.Vec(ToothEntry),
  'created_at' : Timestamp,
  'clinic_id' : ClinicId,
  'treatment_id' : IDL.Opt(TreatmentId),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adjustInventoryStock' : IDL.Func(
      [EntityId, IDL.Float64],
      [IDL.Opt(InventoryItem)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelInvoice' : IDL.Func([EntityId], [IDL.Bool], []),
  'createInventoryItem' : IDL.Func([InventoryItemInput], [InventoryItem], []),
  'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
  'createLabOrder' : IDL.Func([LabOrderInput], [LabOrder], []),
  'createPatient' : IDL.Func([PatientInput], [Patient], []),
  'createPrescription' : IDL.Func([PrescriptionInput], [Prescription], []),
  'createStaffMember' : IDL.Func([StaffInput], [StaffMember], []),
  'createTreatment' : IDL.Func([TreatmentInput], [Treatment], []),
  'deactivatePrescription' : IDL.Func([EntityId], [IDL.Bool], []),
  'deactivateStaffMember' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteInventoryItem' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteLabOrder' : IDL.Func([EntityId], [IDL.Bool], []),
  'deletePatient' : IDL.Func([EntityId], [IDL.Bool], []),
  'deletePrescription' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteTreatment' : IDL.Func([EntityId], [IDL.Bool], []),
  'getAttendanceByDate' : IDL.Func(
      [EntityId, IDL.Text],
      [IDL.Opt(Attendance)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicSettings' : IDL.Func([], [IDL.Opt(ClinicSettings)], ['query']),
  'getDocument' : IDL.Func([EntityId], [IDL.Opt(Document)], ['query']),
  'getExpiryAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(InventoryItem)], ['query']),
  'getInventoryItem' : IDL.Func(
      [EntityId],
      [IDL.Opt(InventoryItem)],
      ['query'],
    ),
  'getInvoice' : IDL.Func([EntityId], [IDL.Opt(Invoice)], ['query']),
  'getLabOrder' : IDL.Func([EntityId], [IDL.Opt(LabOrder)], ['query']),
  'getLowStockAlerts' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getPatient' : IDL.Func([EntityId], [IDL.Opt(Patient)], ['query']),
  'getPrescription' : IDL.Func([EntityId], [IDL.Opt(Prescription)], ['query']),
  'getStaffByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StaffMember)],
      ['query'],
    ),
  'getStaffMember' : IDL.Func([EntityId], [IDL.Opt(StaffMember)], ['query']),
  'getToothChart' : IDL.Func([EntityId], [IDL.Opt(ToothChart)], ['query']),
  'getTreatment' : IDL.Func([EntityId], [IDL.Opt(Treatment)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAttendance' : IDL.Func(
      [IDL.Opt(EntityId), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'listDocuments' : IDL.Func(
      [EntityId, IDL.Text],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'listInvoices' : IDL.Func([IDL.Opt(EntityId)], [IDL.Vec(Invoice)], ['query']),
  'listLabOrders' : IDL.Func(
      [IDL.Opt(EntityId)],
      [IDL.Vec(LabOrder)],
      ['query'],
    ),
  'listPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'listPrescriptions' : IDL.Func(
      [IDL.Opt(EntityId)],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'listStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'listTreatments' : IDL.Func(
      [IDL.Opt(EntityId)],
      [IDL.Vec(Treatment)],
      ['query'],
    ),
  'recordAttendance' : IDL.Func(
      [
        EntityId,
        IDL.Text,
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        AttendanceStatus,
      ],
      [Attendance],
      [],
    ),
  'recordPayment' : IDL.Func([EntityId, Payment], [IDL.Opt(Invoice)], []),
  'searchPatients' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
  'updateClinicSettings' : IDL.Func([ClinicSettings], [ClinicSettings], []),
  'updateInventoryItem' : IDL.Func(
      [EntityId, InventoryItemInput],
      [IDL.Opt(InventoryItem)],
      [],
    ),
  'updateInvoice' : IDL.Func([EntityId, InvoiceInput], [IDL.Opt(Invoice)], []),
  'updateLabOrderStatus' : IDL.Func(
      [EntityId, LabOrderStatus, IDL.Opt(IDL.Text)],
      [IDL.Opt(LabOrder)],
      [],
    ),
  'updatePatient' : IDL.Func([EntityId, PatientInput], [IDL.Opt(Patient)], []),
  'updateStaffMember' : IDL.Func(
      [EntityId, StaffInput],
      [IDL.Opt(StaffMember)],
      [],
    ),
  'updateTreatment' : IDL.Func(
      [EntityId, TreatmentInput],
      [IDL.Opt(Treatment)],
      [],
    ),
  'uploadDocument' : IDL.Func(
      [EntityId, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [Document],
      [],
    ),
  'upsertToothChart' : IDL.Func(
      [EntityId, IDL.Opt(EntityId), IDL.Vec(ToothEntry)],
      [ToothChart],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EntityId = IDL.Nat;
  const ItemId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ClinicId = IDL.Nat;
  const InventoryItem = IDL.Record({
    'id' : ItemId,
    'updated_at' : Timestamp,
    'cost_price' : IDL.Float64,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'reorder_level' : IDL.Float64,
    'clinic_id' : ClinicId,
    'stock' : IDL.Float64,
    'expiry_date' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InventoryItemInput = IDL.Record({
    'cost_price' : IDL.Float64,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'reorder_level' : IDL.Float64,
    'stock' : IDL.Float64,
    'expiry_date' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const PatientId = IDL.Nat;
  const InvoiceItem = IDL.Record({
    'gst_rate' : IDL.Float64,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const InvoiceInput = IDL.Record({
    'patient_id' : PatientId,
    'items' : IDL.Vec(InvoiceItem),
  });
  const InvoiceId = IDL.Nat;
  const InvoiceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'issued' : IDL.Null,
    'partiallyPaid' : IDL.Null,
    'draft' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'other' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
    'netBanking' : IDL.Null,
  });
  const Payment = IDL.Record({
    'method' : PaymentMethod,
    'date' : Timestamp,
    'reference' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'status' : InvoiceStatus,
    'patient_id' : PatientId,
    'total' : IDL.Float64,
    'created_at' : Timestamp,
    'clinic_id' : ClinicId,
    'gst_total' : IDL.Float64,
    'payment_history' : IDL.Vec(Payment),
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Float64,
  });
  const TreatmentId = IDL.Nat;
  const LabOrderInput = IDL.Record({
    'patient_id' : PatientId,
    'specifications' : IDL.Text,
    'lab_name' : IDL.Text,
    'cost' : IDL.Float64,
    'treatment_id' : IDL.Opt(TreatmentId),
    'notes' : IDL.Text,
    'due_date' : IDL.Text,
    'procedure_type' : IDL.Text,
  });
  const LabOrderId = IDL.Nat;
  const LabOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const LabOrder = IDL.Record({
    'id' : LabOrderId,
    'status' : LabOrderStatus,
    'patient_id' : PatientId,
    'specifications' : IDL.Text,
    'lab_name' : IDL.Text,
    'cost' : IDL.Float64,
    'created_at' : Timestamp,
    'clinic_id' : ClinicId,
    'completed_date' : IDL.Opt(IDL.Text),
    'treatment_id' : IDL.Opt(TreatmentId),
    'notes' : IDL.Text,
    'due_date' : IDL.Text,
    'procedure_type' : IDL.Text,
  });
  const BloodGroup = IDL.Variant({
    'abNeg' : IDL.Null,
    'abPos' : IDL.Null,
    'aNeg' : IDL.Null,
    'aPos' : IDL.Null,
    'bNeg' : IDL.Null,
    'bPos' : IDL.Null,
    'oNeg' : IDL.Null,
    'oPos' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PatientInput = IDL.Record({
    'email' : IDL.Text,
    'blood_group' : BloodGroup,
    'address' : IDL.Text,
    'gender' : Gender,
    'first_name' : IDL.Text,
    'last_name' : IDL.Text,
    'date_of_birth' : IDL.Text,
    'phone' : IDL.Text,
    'medical_history' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const Patient = IDL.Record({
    'id' : PatientId,
    'updated_at' : Timestamp,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'clinic_id' : ClinicId,
    'blood_group' : BloodGroup,
    'address' : IDL.Text,
    'gender' : Gender,
    'first_name' : IDL.Text,
    'last_name' : IDL.Text,
    'date_of_birth' : IDL.Text,
    'phone' : IDL.Text,
    'medical_history' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const DentistId = IDL.Nat;
  const Medication = IDL.Record({
    'duration' : IDL.Text,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const PrescriptionInput = IDL.Record({
    'patient_id' : PatientId,
    'dentist_id' : DentistId,
    'medications' : IDL.Vec(Medication),
    'treatment_id' : IDL.Opt(TreatmentId),
  });
  const PrescriptionId = IDL.Nat;
  const Prescription = IDL.Record({
    'id' : PrescriptionId,
    'patient_id' : PatientId,
    'dentist_id' : DentistId,
    'created_at' : Timestamp,
    'clinic_id' : ClinicId,
    'medications' : IDL.Vec(Medication),
    'treatment_id' : IDL.Opt(TreatmentId),
    'is_active' : IDL.Bool,
  });
  const StaffRole = IDL.Variant({
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'receptionist' : IDL.Null,
  });
  const StaffInput = IDL.Record({
    'hire_date' : IDL.Text,
    'license_number' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : StaffRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const StaffId = IDL.Nat;
  const StaffMember = IDL.Record({
    'id' : StaffId,
    'hire_date' : IDL.Text,
    'license_number' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : StaffRole,
    'email' : IDL.Text,
    'clinic_id' : ClinicId,
    'is_active' : IDL.Bool,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const ProcedureStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ToothProcedure = IDL.Record({
    'status' : ProcedureStatus,
    'dentist_id' : DentistId,
    'notes' : IDL.Text,
    'completed_at' : IDL.Opt(Timestamp),
    'procedure_type' : IDL.Text,
    'tooth_number' : IDL.Nat,
  });
  const TreatmentInput = IDL.Record({
    'patient_id' : PatientId,
    'title' : IDL.Text,
    'procedures' : IDL.Vec(ToothProcedure),
    'dentist_id' : DentistId,
    'notes' : IDL.Text,
    'estimated_cost' : IDL.Float64,
  });
  const TreatmentStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Treatment = IDL.Record({
    'id' : TreatmentId,
    'status' : TreatmentStatus,
    'patient_id' : PatientId,
    'title' : IDL.Text,
    'updated_at' : Timestamp,
    'procedures' : IDL.Vec(ToothProcedure),
    'dentist_id' : DentistId,
    'created_at' : Timestamp,
    'clinic_id' : ClinicId,
    'notes' : IDL.Text,
    'estimated_cost' : IDL.Float64,
  });
  const AttendanceStatus = IDL.Variant({
    'halfDay' : IDL.Null,
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : EntityId,
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'staff_id' : EntityId,
    'clinic_id' : ClinicId,
    'check_out' : IDL.Opt(Timestamp),
    'check_in' : IDL.Opt(Timestamp),
  });
  const WorkingHours = IDL.Record({
    'close_time' : IDL.Text,
    'days_open' : IDL.Vec(IDL.Text),
    'open_time' : IDL.Text,
  });
  const ClinicSettings = IDL.Record({
    'gst_number' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'clinic_id' : ClinicId,
    'address' : IDL.Text,
    'working_hours' : WorkingHours,
    'phone' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : EntityId,
    'blob' : ExternalBlob,
    'mime_type' : IDL.Text,
    'clinic_id' : ClinicId,
    'filename' : IDL.Text,
    'owner_id' : EntityId,
    'uploaded_at' : Timestamp,
    'uploaded_by' : IDL.Principal,
    'owner_type' : IDL.Text,
  });
  const ToothStatus = IDL.Variant({
    'missing' : IDL.Null,
    'other' : IDL.Null,
    'implant' : IDL.Null,
    'healthy' : IDL.Null,
    'filled' : IDL.Null,
    'extracted' : IDL.Null,
    'decayed' : IDL.Null,
    'crowned' : IDL.Null,
  });
  const ToothEntry = IDL.Record({
    'status' : ToothStatus,
    'dentist_id' : DentistId,
    'last_updated' : Timestamp,
    'procedure_type' : IDL.Opt(IDL.Text),
    'tooth_number' : IDL.Nat,
  });
  const ToothChart = IDL.Record({
    'id' : EntityId,
    'patient_id' : PatientId,
    'teeth' : IDL.Vec(ToothEntry),
    'created_at' : Timestamp,
    'clinic_id' : ClinicId,
    'treatment_id' : IDL.Opt(TreatmentId),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adjustInventoryStock' : IDL.Func(
        [EntityId, IDL.Float64],
        [IDL.Opt(InventoryItem)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelInvoice' : IDL.Func([EntityId], [IDL.Bool], []),
    'createInventoryItem' : IDL.Func([InventoryItemInput], [InventoryItem], []),
    'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
    'createLabOrder' : IDL.Func([LabOrderInput], [LabOrder], []),
    'createPatient' : IDL.Func([PatientInput], [Patient], []),
    'createPrescription' : IDL.Func([PrescriptionInput], [Prescription], []),
    'createStaffMember' : IDL.Func([StaffInput], [StaffMember], []),
    'createTreatment' : IDL.Func([TreatmentInput], [Treatment], []),
    'deactivatePrescription' : IDL.Func([EntityId], [IDL.Bool], []),
    'deactivateStaffMember' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteInventoryItem' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteLabOrder' : IDL.Func([EntityId], [IDL.Bool], []),
    'deletePatient' : IDL.Func([EntityId], [IDL.Bool], []),
    'deletePrescription' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteTreatment' : IDL.Func([EntityId], [IDL.Bool], []),
    'getAttendanceByDate' : IDL.Func(
        [EntityId, IDL.Text],
        [IDL.Opt(Attendance)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicSettings' : IDL.Func([], [IDL.Opt(ClinicSettings)], ['query']),
    'getDocument' : IDL.Func([EntityId], [IDL.Opt(Document)], ['query']),
    'getExpiryAlerts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getInventoryItem' : IDL.Func(
        [EntityId],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([EntityId], [IDL.Opt(Invoice)], ['query']),
    'getLabOrder' : IDL.Func([EntityId], [IDL.Opt(LabOrder)], ['query']),
    'getLowStockAlerts' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getPatient' : IDL.Func([EntityId], [IDL.Opt(Patient)], ['query']),
    'getPrescription' : IDL.Func(
        [EntityId],
        [IDL.Opt(Prescription)],
        ['query'],
      ),
    'getStaffByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StaffMember)],
        ['query'],
      ),
    'getStaffMember' : IDL.Func([EntityId], [IDL.Opt(StaffMember)], ['query']),
    'getToothChart' : IDL.Func([EntityId], [IDL.Opt(ToothChart)], ['query']),
    'getTreatment' : IDL.Func([EntityId], [IDL.Opt(Treatment)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAttendance' : IDL.Func(
        [IDL.Opt(EntityId), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'listDocuments' : IDL.Func(
        [EntityId, IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'listInvoices' : IDL.Func(
        [IDL.Opt(EntityId)],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'listLabOrders' : IDL.Func(
        [IDL.Opt(EntityId)],
        [IDL.Vec(LabOrder)],
        ['query'],
      ),
    'listPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'listPrescriptions' : IDL.Func(
        [IDL.Opt(EntityId)],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'listStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'listTreatments' : IDL.Func(
        [IDL.Opt(EntityId)],
        [IDL.Vec(Treatment)],
        ['query'],
      ),
    'recordAttendance' : IDL.Func(
        [
          EntityId,
          IDL.Text,
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          AttendanceStatus,
        ],
        [Attendance],
        [],
      ),
    'recordPayment' : IDL.Func([EntityId, Payment], [IDL.Opt(Invoice)], []),
    'searchPatients' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
    'updateClinicSettings' : IDL.Func([ClinicSettings], [ClinicSettings], []),
    'updateInventoryItem' : IDL.Func(
        [EntityId, InventoryItemInput],
        [IDL.Opt(InventoryItem)],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [EntityId, InvoiceInput],
        [IDL.Opt(Invoice)],
        [],
      ),
    'updateLabOrderStatus' : IDL.Func(
        [EntityId, LabOrderStatus, IDL.Opt(IDL.Text)],
        [IDL.Opt(LabOrder)],
        [],
      ),
    'updatePatient' : IDL.Func(
        [EntityId, PatientInput],
        [IDL.Opt(Patient)],
        [],
      ),
    'updateStaffMember' : IDL.Func(
        [EntityId, StaffInput],
        [IDL.Opt(StaffMember)],
        [],
      ),
    'updateTreatment' : IDL.Func(
        [EntityId, TreatmentInput],
        [IDL.Opt(Treatment)],
        [],
      ),
    'uploadDocument' : IDL.Func(
        [EntityId, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [Document],
        [],
      ),
    'upsertToothChart' : IDL.Func(
        [EntityId, IDL.Opt(EntityId), IDL.Vec(ToothEntry)],
        [ToothChart],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };